In [21]:
import pickle, glob
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier

### Loading the Data

In [2]:
path = '*.bin'
files = glob.glob(path)
signal = [0,0,0,0,0]
for i,f in enumerate(files):
    with open(f, 'rb') as fp:
        signal[i] = pickle.load(fp)

In [3]:
signal1 = np.array(signal[0], dtype = 'O')
signal2 = np.array(signal[1], dtype = 'O')
signal3 = np.array(signal[2], dtype = 'O')
signal4 = np.array(signal[3], dtype = 'O')
signal5 = np.array(signal[4], dtype = 'O')

### Data Preprocessing

In [4]:
signal1 = pd.DataFrame(signal1, columns = ['X'])
signal1['Y'] = 0

signal2 = pd.DataFrame(signal2, columns = ['X'])
signal2['Y'] = 1

signal3 = pd.DataFrame(signal3, columns = ['X'])
signal3['Y'] = 2

signal4 = pd.DataFrame(signal4, columns = ['X'])
signal4['Y'] = 3

signal5 = pd.DataFrame(signal5, columns = ['X'])
signal5['Y'] = 4

In [5]:
data = signal1.append(signal2, ignore_index = True)
data = data.append(signal3, ignore_index = True)
data = data.append(signal4, ignore_index = True)
data = data.append(signal5, ignore_index = True)

In [6]:
length = data['X'].str.len()
m= max(length)

x = []
for i in range(0,len(data)):
    i_length = len(data['X'][i])
    old = data['X'][i]
    if i_length < m:
        new = [0] * (m - i_length)
        x.append(old + new)
    else:
        x.append(old)
for i in range(0,len(data)):
    t = [str(j) for j in data['X'][i]]
    data['X'][i] = ' '.join(t)

    
x = data['X'].values
y = data['Y'].values


### Feature Selection

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x = tf.fit_transform(x).toarray()

<ipython-input-7-038f0ebf86b7>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['X'][i] = ' '.join(t)


### Splitting the dataset into train and test

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

### Logistic Regression

In [9]:
lr = LogisticRegression(random_state=0, n_jobs=-1 )
lr.fit(x_train,y_train)

LogisticRegression(n_jobs=-1, random_state=0)

In [10]:
y_pred = lr.predict(x_test)

In [12]:
cm = confusion_matrix(y_test,y_pred)
score = accuracy_score(y_test,y_pred)
report = classification_report(y_test, y_pred)

D:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [13]:
score

0.30566037735849055

In [14]:
cm

array([[66,  0,  5,  0,  0],
       [30,  0,  7,  0,  3],
       [47,  0,  9,  8,  0],
       [53,  0,  9,  0,  0],
       [21,  0,  1,  0,  6]], dtype=int64)

### Random Forest

In [16]:
rf = RandomForestClassifier(n_estimators=100, random_state = 0 , n_jobs = -1 )
rf.fit(x_train,y_train)

RandomForestClassifier(n_jobs=-1, random_state=0)

In [17]:
y_pred = rf.predict(x_test)

In [18]:
cm = confusion_matrix(y_test,y_pred)
score = accuracy_score(y_test,y_pred)
report = classification_report(y_test, y_pred)

In [19]:
score

0.29056603773584905

In [20]:
cm

array([[40,  0,  3, 26,  2],
       [24,  1,  4,  6,  5],
       [26,  1,  5, 32,  0],
       [31,  1,  8, 22,  0],
       [10,  0,  0,  9,  9]], dtype=int64)

### SVM

In [22]:
sv = SVC( kernel = 'linear' , random_state=0 )
sv.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [23]:
y_pred = sv.predict(x_test)

In [24]:
cm = confusion_matrix(y_test,y_pred)
score = accuracy_score(y_test,y_pred)
report = classification_report(y_test, y_pred)

In [25]:
score

0.32452830188679244

In [26]:
cm

array([[67,  0,  4,  0,  0],
       [30,  1,  4,  0,  5],
       [47,  0, 10,  7,  0],
       [53,  0,  9,  0,  0],
       [19,  0,  1,  0,  8]], dtype=int64)

### Implementing CNN

In [40]:
import pickle, glob
import numpy as np
import pandas as pd

path = './*.bin'
files = glob.glob(path)
signal = [0,0,0,0,0]
for i,f in enumerate(files):
    with open(f, 'rb') as fp:
        signal[i] = pickle.load(fp)


signal1 = np.array(signal[4], dtype = 'O')
signal2 = np.array(signal[3], dtype = 'O')
signal3 = np.array(signal[2], dtype = 'O')
signal4 = np.array(signal[1], dtype = 'O')
signal5 = np.array(signal[0], dtype = 'O')


signal1 = pd.DataFrame(signal1, columns = ['X'])
signal1['Y'] = 0

signal2 = pd.DataFrame(signal2, columns = ['X'])
signal2['Y'] = 1

signal3 = pd.DataFrame(signal3, columns = ['X'])
signal3['Y'] = 2

signal4 = pd.DataFrame(signal4, columns = ['X'])
signal4['Y'] = 3

signal5 = pd.DataFrame(signal5, columns = ['X'])
signal5['Y'] = 4


data = signal1.append(signal2, ignore_index = True)
data = data.append(signal3, ignore_index = True)
data = data.append(signal4, ignore_index = True)
data = data.append(signal5, ignore_index = True)

'''
for i in range(0,len(data)):
    t = [str(j) for j in data['X'][i]]
    data['X'][i] = ' '.join(t)
    
x = data['X'].values
y = data['Y'].values


from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x = tf.fit_transform(x).toarray()
'''

length = data['X'].str.len()
m = max(length)


for i in range(0,len(data)):
    i_length = len(data['X'][i])
    if i_length < m:
        new = [-10] * (m - i_length)
        data['X'][i] += new


x = data['X'].values
y = data['Y'].values

x_new = []
for i in x:
    x_new.append(i)

x_new = np.array(x_new)

max_element = np.max(x_new)

#x_new = x_new/max_element

x_new = np.reshape(x_new, (x_new.shape[0], x_new.shape[1],1))

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size = 0.25, random_state = 0)


'''
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=5, activation='softmax'))
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
ann.fit(x_train, y_train, batch_size = 32, epochs = 50)

y_pred = ann.predict(x_test)

y_p = []
for i in y_pred:
    m = max(i)
    k = list(i).index(m)
    y_p.append(k)

'''

'''
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train,y_train)
'''



from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D , MaxPool1D, Flatten, Masking

cnn = Sequential()

cnn.add(Masking(mask_value = -10))

cnn.add(Conv1D(filters= 32, kernel_size= 2, strides= 1, activation='relu'))
cnn.add(MaxPool1D(pool_size=2, strides= 1))

cnn.add(Conv1D(filters= 32, kernel_size= 2, strides= 1, activation='relu'))
cnn.add(MaxPool1D(pool_size=2, strides= 1))

cnn.add(Flatten())

cnn.add(Dense(units = 100, activation = 'relu'))
cnn.add(Dense(units = 50, activation = 'relu'))

cnn.add(Dense(units = 5, activation = 'softmax'))

cnn.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

cnn.fit(x_train, y_train, epochs = 100, batch_size = 32)
y_p = cnn.predict(x_test)


y_pred = []

for i in y_p:
    mx = max(i)
    v = list(i).index(mx)
    y_pred.append(v)



from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
cm = confusion_matrix(y_test,y_pred)
score = accuracy_score(y_test,y_pred)
report = classification_report(y_test, y_pred)

<ipython-input-40-eac6cabfb9ff>:63: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['X'][i] += new


Epoch 1/100
25/25 [==============================] - 2s 32ms/step - loss: 2.1480 - accuracy: 0.2666
Epoch 2/100
25/25 [==============================] - 1s 32ms/step - loss: 1.5235 - accuracy: 0.3579
Epoch 3/100
25/25 [==============================] - 1s 34ms/step - loss: 1.4062 - accuracy: 0.3922
Epoch 4/100
25/25 [==============================] - 1s 33ms/step - loss: 1.3800 - accuracy: 0.3917
Epoch 5/100
25/25 [==============================] - 1s 34ms/step - loss: 1.3067 - accuracy: 0.4282
Epoch 6/100
25/25 [==============================] - 1s 32ms/step - loss: 1.2958 - accuracy: 0.4367
Epoch 7/100
25/25 [==============================] - 1s 34ms/step - loss: 1.2875 - accuracy: 0.4456
Epoch 8/100
25/25 [==============================] - 1s 32ms/step - loss: 1.2360 - accuracy: 0.4803 0s - loss: 1.2337 - accu
Epoch 9/100
25/25 [==============================] - 1s 34ms/step - loss: 1.1750 - accuracy: 0.5039
Epoch 10/100
25/25 [==============================] - 1s 33ms/step - loss: 

In [41]:
score

0.3132075471698113

In [42]:
cm

array([[ 9,  2,  5,  1,  7],
       [ 1,  9, 11,  2, 22],
       [ 4, 15, 15,  6, 20],
       [ 3,  2,  8,  9, 18],
       [ 6, 14, 31,  4, 41]], dtype=int64)

### Implementing RNN

In [45]:
import pickle, glob
import numpy as np
import pandas as pd

path = './*.bin'
files = glob.glob(path)
signal = [0,0,0,0,0]
for i,f in enumerate(files):
    with open(f, 'rb') as fp:
        signal[i] = pickle.load(fp)


signal1 = np.array(signal[4], dtype = 'O')
signal2 = np.array(signal[3], dtype = 'O')
signal3 = np.array(signal[2], dtype = 'O')
signal4 = np.array(signal[1], dtype = 'O')
signal5 = np.array(signal[0], dtype = 'O')


signal1 = pd.DataFrame(signal1, columns = ['X'])
signal1['Y'] = 0

signal2 = pd.DataFrame(signal2, columns = ['X'])
signal2['Y'] = 1

signal3 = pd.DataFrame(signal3, columns = ['X'])
signal3['Y'] = 2

signal4 = pd.DataFrame(signal4, columns = ['X'])
signal4['Y'] = 3

signal5 = pd.DataFrame(signal5, columns = ['X'])
signal5['Y'] = 4


data = signal1.append(signal2, ignore_index = True)
data = data.append(signal3, ignore_index = True)
data = data.append(signal4, ignore_index = True)
data = data.append(signal5, ignore_index = True)

'''
for i in range(0,len(data)):
    t = [str(j) for j in data['X'][i]]
    data['X'][i] = ' '.join(t)
    
x = data['X'].values
y = data['Y'].values


from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x = tf.fit_transform(x).toarray()
'''

length = data['X'].str.len()
m = max(length)


for i in range(0,len(data)):
    i_length = len(data['X'][i])
    if i_length < m:
        new = [-10] * (m - i_length)
        data['X'][i] += new


x = data['X'].values
y = data['Y'].values

x_new = []
for i in x:
    x_new.append(i)

x_new = np.array(x_new)

max_element = np.max(x_new)

#x_new = x_new/max_element

x_new = np.reshape(x_new, (x_new.shape[0], x_new.shape[1],1))

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size = 0.25, random_state = 0)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , LSTM, Dropout, Masking

rnn = Sequential()

rnn.add(Masking(mask_value = -10,input_shape = (x_train.shape[1], 1)))
rnn.add(LSTM(units = 100, return_sequences=True))
rnn.add(Dropout(0.2))

rnn.add(LSTM(units = 100, return_sequences=True))
rnn.add(Dropout(0.2))

rnn.add(LSTM(units = 100))
rnn.add(Dropout(0.2))

rnn.add(Dense(units = 1, activation = 'softmax'))

rnn.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

rnn.fit(x_train, y_train, epochs = 100, batch_size = 32)

y_pred = rnn.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
cm = confusion_matrix(y_test,y_pred)
score = accuracy_score(y_test,y_pred)
report = classification_report(y_test, y_pred)

<ipython-input-45-f5d05dd88d00>:71: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['X'][i] += new


Epoch 1/100
25/25 [==============================] - 32s 885ms/step - loss: 0.0000e+00 - accuracy: 0.1941
Epoch 2/100
25/25 [==============================] - 22s 872ms/step - loss: 0.0000e+00 - accuracy: 0.1965
Epoch 3/100
25/25 [==============================] - 22s 880ms/step - loss: 0.0000e+00 - accuracy: 0.2119
Epoch 4/100
25/25 [==============================] - 22s 889ms/step - loss: 0.0000e+00 - accuracy: 0.1915
Epoch 5/100
25/25 [==============================] - 22s 894ms/step - loss: 0.0000e+00 - accuracy: 0.2229
Epoch 6/100
25/25 [==============================] - 22s 870ms/step - loss: 0.0000e+00 - accuracy: 0.1904
Epoch 7/100
25/25 [==============================] - 21s 859ms/step - loss: 0.0000e+00 - accuracy: 0.2094
Epoch 8/100
25/25 [==============================] - 21s 855ms/step - loss: 0.0000e+00 - accuracy: 0.2115
Epoch 9/100
25/25 [==============================] - 22s 860ms/step - loss: 0.0000e+00 - accuracy: 0.1877
Epoch 10/100
25/25 [==========================

D:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [46]:
score

0.16981132075471697

In [47]:
cm

array([[ 0, 24,  0,  0,  0],
       [ 0, 45,  0,  0,  0],
       [ 0, 60,  0,  0,  0],
       [ 0, 40,  0,  0,  0],
       [ 0, 96,  0,  0,  0]], dtype=int64)

### With Discretization, trying out the models

In [48]:
import pickle, glob
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [49]:
path = './*.bin'
files = glob.glob(path)
signal = [0,0,0,0,0]
for i,f in enumerate(files):
    with open(f, 'rb') as fp:
        signal[i] = pickle.load(fp)

In [50]:
signal1 = np.array(signal[0], dtype = 'O')
signal2 = np.array(signal[1], dtype = 'O')
signal3 = np.array(signal[2], dtype = 'O')
signal4 = np.array(signal[3], dtype = 'O')
signal5 = np.array(signal[4], dtype = 'O')

In [51]:
signal1 = pd.DataFrame(signal1, columns = ['X'])
signal1['Y'] = 0

signal2 = pd.DataFrame(signal2, columns = ['X'])
signal2['Y'] = 1

signal3 = pd.DataFrame(signal3, columns = ['X'])
signal3['Y'] = 2

signal4 = pd.DataFrame(signal4, columns = ['X'])
signal4['Y'] = 3

signal5 = pd.DataFrame(signal5, columns = ['X'])
signal5['Y'] = 4

In [52]:
data = signal1.append(signal2, ignore_index = True)
data = data.append(signal3, ignore_index = True)
data = data.append(signal4, ignore_index = True)
data = data.append(signal5, ignore_index = True)

In [53]:
data

X  Y
0     [60.63778305053711, 60.53467178344727, 60.7472...  0
1     [2.22484302520752, 1.474851489067078, 0.970637...  0
2     [1.382016181945801, 0.9838278889656067, 1.5994...  0
3     [64.96823120117188, 64.86775207519531, 62.7523...  0
4     [26.47737503051758, 27.5166072845459, 28.87783...  0
...                                                 ... ..
1053  [3.033940315246582, 2.313158512115479, 2.31514...  4
1054  [54.61786270141602, 54.92446517944336, 55.2440...  4
1055  [49.94552612304688, 50.17890167236328, 49.8320...  4
1056  [59.90553665161133, 59.5039176940918, 59.91153...  4
1057  [57.41999816894531, 58.49517822265625, 59.8477...  4

[1058 rows x 2 columns]

In [54]:
length = data['X'].str.len()
m= max(length)

x = []
for i in range(0,len(data)):
    i_length = len(data['X'][i])
    old = data['X'][i]
    if i_length < m:
        new = [0] * (m - i_length)
        x.append(old + new)
    else:
        x.append(old)

In [55]:
x = np.array(x)
y = data['Y'].values
df = pd.DataFrame(x)
df['y'] = y
df = df.drop('y', axis = 1)

In [56]:
def r(a):
    return round(a,2)

for i in range(0,477):
    df[i] = df[i].apply(r)

In [57]:
df['y'] = data['Y'].values

In [58]:
df['y']
df.to_csv("d.csv", index=False)

In [59]:
data = pd.read_csv('d.csv')

In [60]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [61]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state =0)

In [66]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.pipeline import Pipeline
# ensure inputs are floats and output is an integer label
X = X.astype('float32')
y = LabelEncoder().fit_transform(y.astype('str'))
# define the pipeline
trans = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
model = KNeighborsClassifier()
pipeline = Pipeline(steps=[('t', trans), ('m', model)])
# evaluate the pipeline
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(pipeline, x_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
# report pipeline performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.343 (0.044)
